import fs from "node:fs";
import path from "node:path";
import { findPackageRoot } from "./utils.js";
import { WrapperLaunchConfig } from "./index.js";

/// In development, use the jar generated by the local build (if available)
const PACKAGE_ROOT = findPackageRoot();
const WRAPPER_JAR_DEVELOPMENT_FOLDER = path.join(PACKAGE_ROOT, "../rumble-lsp-wrapper/target");
const WRAPPER_RUNTIME_CLASSPATH_FILE = "runtime-classpath.txt";
const WRAPPER_MAIN_CLASS = "org.jsoniq.lsp.rumble.Main";
const WRAPPER_JAR_NAME_PREFIX = "rumble-lsp-wrapper";

export function resolveDevLaunchConfig(): WrapperLaunchConfig | undefined {
    const localJarPath = pickLatestJarFromDirectory(WRAPPER_JAR_DEVELOPMENT_FOLDER);
    const classpathPath = path.join(WRAPPER_JAR_DEVELOPMENT_FOLDER, WRAPPER_RUNTIME_CLASSPATH_FILE);
    if (localJarPath === undefined || !fs.existsSync(classpathPath)) {
        return undefined;
    }

    const runtimeClasspath = fs.readFileSync(classpathPath, "utf8").trim();
    const classpath = runtimeClasspath.length === 0
        ? localJarPath
        : `${localJarPath}${path.delimiter}${runtimeClasspath}`;

    return {
        args: ["-cp", classpath, WRAPPER_MAIN_CLASS, "--daemon"],
    };
}

function pickLatestJarFromDirectory(
    directory: string,
): string | undefined {
    if (!fs.existsSync(directory)) {
        return undefined;
    }

    const files = fs.readdirSync(directory);
    const wrapperJars = files
        .filter((file) => file.startsWith(WRAPPER_JAR_NAME_PREFIX) && file.endsWith(".jar"))
        .map((file) => path.join(directory, file))
        .sort((a, b) => fs.statSync(b).mtime.getTime() - fs.statSync(a).mtime.getTime());

    return wrapperJars[0];
}
